### ISSUE TITLE
Caveats with Smartscreen and Smart App Control

### ISSUE THREAD

**Issue by tommytran732** [beerisgood/Windows11_Hardening#17]
Apparently, Smartscreen sends the full URL to Microsoft instead of doing hashing like with Google Safe Browsing. 

I am not entirely sure recommending that users enable it willy nilly is a good idea, considering that a lot of times sensitive information gets put into the URL (sometimes it can contain the decryption keys for encrypted file sharing for example, and other times it may contain username and passwords in there).

https://www.bleepingcomputer.com/news/microsoft/windows-10-smartscreen-sends-urls-and-app-names-to-microsoft/

"Check app and files" is less bad, since it is only metadata. It still carries some privacy implications though. Smart App Control forces this setting to be enabled, so it's not just local signature checking.

**Comment by beerisgood** [comment]
I don’t read anything really bad in terms of privacy about this feature but the security is greatly improved.

**Comment by tommytran732** [comment]
> I don’t read anything really bad in terms of privacy about this feature but the security is greatly improved.

Well I think the full URL being sent with Edge is pretty bad. Consider scenarios where you use Proton Drive/Mega/PrivateBin which appends the encryption key in the URL. Now you are sending both the URL and the key to Microsoft.

**Comment by tommytran732** [comment]
Just to be clear - there are 2 different things here:

- Sending full URL of the links you visit: this is really, really bad. Probably not worth it since it is just badness enumeration.
- Sending metadata about executables: this is whatever. Just something to be aware of and manage depending on the threat model.

**Comment by beerisgood** [comment]
> Consider scenarios where you use Proton Drive/Mega/PrivateBin which append the encryption key in the URL. Now you are sending both the URL and the key to Microsoft. Something that's supposed to be private / end-to-end encrypted now gets leaked just like that. Or if you use PHPMyAdmin with the username & password appended for logins - now you are leaking access to your database.

This isn’t Microsoft fault and shouldn’t be the case with any service which takes security seriously.

I get your points but I will not remove the recommendation.

**Comment by tommytran732** [comment]
> I get your points but I will not remove the recommendation.

I am not saying that you should remove it, but you probably should put a disclaimer on there.

**Comment by beerisgood** [comment]
You can take a look at my Windows privacy repository which links to Microsoft privacy documents.
