### ISSUE TITLE
OneDrive prevent personal accounts

### ISSUE THREAD

**Issue by digitaljdr** [beerisgood/Windows11_Hardening#20]
After I applied the hardening presets I see now that its also preventing personal onedrive accounts from being used, this isn't called out anywhere in the guide.

**Comment by beerisgood** [comment]
That’s new to me. 
which setting did you mean?

**Comment by digitaljdr** [comment]
I had to load the onedrive admx template to actually see it. It was a user configuration in group policy that was set to enable. 
![2023-11-13 08_11_32-Local Group Policy Editor](https://github.com/beerisgood/Windows11_Hardening/assets/712854/8483b33d-c2b2-406a-907b-7543120958be)

**Comment by beerisgood** [comment]
> I had to load the onedrive admx template to actually see it. It was a user configuration in group policy that was set to enable. ![2023-11-13 08_11_32-Local Group Policy Editor](https://user-images.githubusercontent.com/712854/282469723-8483b33d-c2b2-406a-907b-7543120958be.png)

As I doesn’t provide any templates which one did you use with this broken onedrive config?

**Comment by digitaljdr** [comment]
The templates are added to your machine as part of the install process ironically enough. 

%localappdata%\Microsoft\OneDrive\<BuildNumber>\adm

**Comment by beerisgood** [comment]
I still don’t understand why onedrive is blocked for you. 

Did you use the Hard_Configurator tool / or start the problem after using it?

**Comment by digitaljdr** [comment]
I used the gui tool and rebooted and couldn't sign in using my personal account on my personal machine - I get that it might be a hardening tool for use in businesses preventing people from signing into personal Onedrives on work machines but again the guide doesn't say that. 

I found a couple of folders of policies that were applied 

![2023-11-13 14_04_08-C__Users_GhostW_Downloads_Windows-Optimize-Harden-Debloat_v1 0 1_Files_GPOs_DoD_](https://github.com/beerisgood/Windows11_Hardening/assets/712854/c3ef9ca9-ef02-4d6f-8214-bb4f27ece182)
![2023-11-13 14_04_39-C__Users_GhostW_Downloads_Windows-Optimize-Harden-Debloat_v1 0 1_Files_GPOs_SoS_](https://github.com/beerisgood/Windows11_Hardening/assets/712854/77c04b8c-307a-42e5-9aad-0a3df3094dd3)

ill continue looking where it was applied.

**Comment by beerisgood** [comment]
> I used the gui tool and rebooted and couldn't sign in using my personal account on my personal machine - I get that it might be a hardening tool for use in businesses preventing people from signing into personal Onedrives on work machines but again the guide doesn't say that.
> 
> I found a couple of folders of policies that were applied
> 
> ![2023-11-13 14_04_08-C__Users_GhostW_Downloads_Windows-Optimize-Harden-Debloat_v1 0 1_Files_GPOs_DoD_](https://user-images.githubusercontent.com/712854/282563305-c3ef9ca9-ef02-4d6f-8214-bb4f27ece182.png) ![2023-11-13 14_04_39-C__Users_GhostW_Downloads_Windows-Optimize-Harden-Debloat_v1 0 1_Files_GPOs_SoS_](https://user-images.githubusercontent.com/712854/282563306-77c04b8c-307a-42e5-9aad-0a3df3094dd3.png)
> 
> ill continue looking where it was applied.

Don’t know where you get that files but I don’t link anywhere to „Downloads_Windows-Optimize-Harden-Debloat“ as I’m against such tools. 

Doesn’t sound like that is a problem with my guide so I close it now. Restore your system to default and follow my guide again, without any external tools. 
the only one recommend is Hard_Configurator.
